milblog/blogppal/urls.py
from django.urls import path
from . import views

app_name = "blogppal"

urlpatterns = [
    # Vistas posts
    path("", views.post_list, name="post_list"),
    path("<int:id>/", views.post_detail, name="post_detail"),
]

milblog/milblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blogppal/", include("blogppal.urls", namespace="blogppal")),
]

milblog/blogppal/models.py
from django.db import models
from django.utils import timezone #Agregamos librerias para controlar las fechas de los posteos
from django.contrib.auth.models import User
# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLICADO)


class Post(models.Model):

    class Status(models.TextChoices):
        BORRADOR = 'BR', 'Borrador'
        PUBLICADO = 'PB', 'Publicado'

    titulo_post = models.CharField(max_length= 250) #Titulo del posteo a cargar
    slug = models.SlugField(max_length=250) #Mas adelante va a servir para busquedas
    autor = models.ForeignKey(User, on_delete= models.CASCADE, related_name='blog_posts')
    cuerpo_post = models.TextField() #Cuerpo del posteo.
    publicado = models.DateTimeField(default=timezone.now)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, 
                              choices = Status.choices,
                              default = Status.BORRADOR)
    objects = models.Manager()
    publicac = PublishedManager()

    class Meta:
        ordering = ['publicado'] #Le indicamos que se va a ordenar por fecha de publicacion
        indexes = [models.Index(fields=['publicado']),]

    def __str__(self):
        return self.titulo_post #Esto lo usamos para definir el nombre y usarlo en varias aplicaciones

milblog/blogppal/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


# Create your views here.
def post_list(request):
    posts = Post.publicac.all()
    return render(request, "blog/post/list.html", {"posts": posts})


def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLICADO)

    return render(request, "blog/post/detail.html", {"post": post})

milblog/blogppal/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
    </head>

    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>Mi blog</h2>
            <p>Este es el blog militar</p>
        </div>
    </body>
</html>

milblog/blogppal/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.titulo_post }}{% endblock %}

{% block content %}
   <h1>{{ post.titulo_post }}</h1>
   <p class="date">
      Publicado {{ post.publicado }} por {{ post.autor }}
   </p>
   {{ post.cuerpo_post|linebreaks }}
{% endblock %}

milblog/blogppal/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mi Blog{% endblock %}

{% block content %}
   <h1>Mi Blog</h1>
   <!--{% if posts %}-->
      {% for post in posts %}
       <h2>
           <a href="{% url 'blogppal:post_detail' post.id %}">
            {{ post.titulo_post }}
           </a>
       </h2>
       <p class="date">
         Publicado {{ post.publicado }} por {{ post.autor }}
       </p>
       {{ post.cuerpo_post|truncatewords:30|linebreaks }}
      {% endfor %}
    <!--{% else %}
       <p>No hay post</p>
    {% endif %}-->
{% endblock %}